terraform {
  required_version = ">= 1.6.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.37"
    }
    archive = {
      source  = "hashicorp/archive"
      version = "~> 2.7"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

locals {
  function_name         = var.function_name
  notifications_enabled = trimspace(var.notification_email) != ""
  pushover_enabled      = trimspace(var.pushover_user_key) != "" && trimspace(var.pushover_app_token) != ""
}

resource "aws_iam_role" "lambda_exec" {
  name = "${local.function_name}-exec"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Principal = {
          Service = "lambda.amazonaws.com"
        }
        Action = "sts:AssumeRole"
      }
    ]
  })
}

resource "aws_iam_role_policy_attachment" "basic_execution" {
  role       = aws_iam_role.lambda_exec.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

resource "aws_iam_role_policy" "sns_publish" {
  count = local.notifications_enabled ? 1 : 0

  name = "${local.function_name}-sns-publish"
  role = aws_iam_role.lambda_exec.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = ["sns:Publish"]
        Resource = aws_sns_topic.unlock_notifications[0].arn
      }
    ]
  })
}

data "archive_file" "lambda_zip" {
  type        = "zip"
  source_dir  = "${path.module}/lambda"
  output_path = "${path.module}/lambda.zip"
}

resource "aws_lambda_function" "door_opener" {
  function_name    = local.function_name
  role             = aws_iam_role.lambda_exec.arn
  runtime          = "python3.13"
  handler          = "app.lambda_handler"
  filename         = data.archive_file.lambda_zip.output_path
  source_code_hash = data.archive_file.lambda_zip.output_base64sha256
  timeout          = 15
  memory_size      = 256

  environment {
    variables = {
      SWITCHBOT_TOKEN        = var.switchbot_token
      SWITCHBOT_SECRET       = var.switchbot_secret
      LINK_SIGNING_SECRET    = var.link_signing_secret
      DEVICE_ID              = var.device_id
      LINK_TTL_SECONDS       = tostring(var.link_ttl_seconds)
      NOTIFICATION_TOPIC_ARN = local.notifications_enabled ? aws_sns_topic.unlock_notifications[0].arn : ""
      PUSHOVER_USER_KEY      = local.pushover_enabled ? var.pushover_user_key : ""
      PUSHOVER_APP_TOKEN     = local.pushover_enabled ? var.pushover_app_token : ""
      PUSHOVER_DEVICE        = trimspace(var.pushover_device)
    }
  }
}

resource "aws_lambda_function_url" "door_opener" {
  function_name      = aws_lambda_function.door_opener.function_name
  authorization_type = "NONE"

  cors {
    allow_origins = ["*"]
    allow_methods = ["GET"]
    allow_headers = ["*"]
    max_age       = 3600
  }
}

resource "aws_lambda_permission" "function_url_invoke" {
  statement_id           = "AllowPublicFunctionUrlInvoke"
  action                 = "lambda:InvokeFunctionUrl"
  function_name          = aws_lambda_function.door_opener.function_name
  principal              = "*"
  function_url_auth_type = "NONE"
}

resource "aws_lambda_permission" "function_invoke" {
  statement_id             = "AllowPublicInvokeForFunctionUrl"
  action                   = "lambda:InvokeFunction"
  function_name            = aws_lambda_function.door_opener.function_name
  principal                = "*"
  invoked_via_function_url = true
}

resource "aws_cloudwatch_log_group" "door_opener" {
  name              = "/aws/lambda/${aws_lambda_function.door_opener.function_name}"
  retention_in_days = 14
}

resource "aws_sns_topic" "unlock_notifications" {
  count = local.notifications_enabled ? 1 : 0

  name = "${local.function_name}-unlock-notifications"
}

resource "aws_sns_topic_subscription" "email" {
  count = local.notifications_enabled ? 1 : 0

  topic_arn = aws_sns_topic.unlock_notifications[0].arn
  protocol  = "email"
  endpoint  = trimspace(var.notification_email)
}

resource "local_file" "local_env" {
  filename = "${path.module}/.env"
  content  = <<-EOT
    # Generated by Terraform. Safe to re-create with terraform apply.
    BASE_URL=${aws_lambda_function_url.door_opener.function_url}
  EOT
}
